version: '3.8'
services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    volumes:
      - ./wwebjs_auth:/app/.wwebjs_auth  # Mantiene l'autenticazione tra riavvii
    environment:
      - NODE_ENV=production
